name: 'action-pm2-deploy'
description: 'Deploy a web app via pm2'
author: "Tyler O'Brien"
inputs:
  host:
    description: 'Hostname or IP address of remote to copy to'
    required: true
  port:
    description: 'Port to use for scp operation'
    default: 22
  user:
    description: 'Username of remote user'
    required: true
  key:
    description: 'Private SSH key used to identify remote user'
    required: true
  proxy_disabled:
    description: 'Set to 1 to disable the use of proxy'
    required: true
  proxy_host:
    description: 'Hostname or IP address of proxy'
    required: true
  proxy_port:
    description: 'Port to use for proxy ssh connection'
    default: 22
  proxy_user:
    description: 'Username of proxy user'
    default: 'bastion'
  proxy_key:
    description: 'Private SSH key used to identify proxy user'
    required: true
  source:
    description: 'Filepath of source'
    required: true
  destination:
    description: 'Filepath of destination'
    required: true
  npm:
    description: 'Set to 1 if npm and not yarn is being used'
    default: '0'
  command:
    description: 'The npm script that will be run for the build operation'
    default: 'build'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'copy'
  color: 'orange'
